# -*- coding: utf-8 -*-
"""FP AMCC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109Q70wkCz0YfnqjridB2u7ZsNrIfJtIf

IMPORT LIBRAY
"""

#from google.colab import drive
#drive.mount('models/drive')

# streamlit
import joblib
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
import joblib
import shap

from scipy.optimize import linprog
from sklearn.ensemble import RandomForestRegressor, IsolationForest
from sklearn.model_selection import (train_test_split, GridSearchCV,
                                     learning_curve, cross_val_score)
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

warnings.filterwarnings("ignore")

"""PEWARNAAN SETIAP REGION"""

REGION_COLORS = ["#2E86AB", "#A23B72", "#F18F01", "#C73E1D", "#3B1F2B"]
REGIONS       = ["Garut", "Indramayu", "Karawang", "Subang", "Tasikmalaya"]
RANDOM_STATE  = 42
np.random.seed(RANDOM_STATE)

plt.style.use("seaborn-v0_8-whitegrid")
pd.set_option("display.float_format", lambda x: f"{x:,.0f}")
pd.set_option("display.max_columns", 20)

df = pd.read_excel("data/data2.xlsx")
df.isnull().sum()

"""DATA ACQUISITION"""

FILE_PATH = "data/data2.xlsx"

def parse_regional_sheet(file_path: str,
                         sheet_name: str,
                         actor_type: str) -> pd.DataFrame:
    """
    Mem-parse satu sheet Excel multi-wilayah menjadi satu DataFrame bersih.

    Setiap sheet mengandung sub-tabel per wilayah yang dipisahkan oleh
    baris nama wilayah. Fungsi ini mendeteksi dan menggabungkan semua
    sub-tabel tersebut.

    Parameters
    ----------
    file_path  : str  — path ke file .xlsx
    sheet_name : str  — nama sheet yang akan di-parse
    actor_type : str  — label aktor ('Farmer', 'Miller', dll.)

    Returns
    -------
    pd.DataFrame dengan kolom tambahan 'region' dan 'actor_type'
    """
    # Baca tanpa header supaya bisa mengontrol parsing sendiri
    df_raw = pd.read_excel(file_path, sheet_name=sheet_name, header=None)

    collected   = []      # list of DataFrame per wilayah
    cur_region  = None
    header_cols = None
    row_buffer  = []

    for _, row in df_raw.iterrows():
        first_cell = str(row.iloc[0]).strip() if pd.notna(row.iloc[0]) else ""

        # ── Deteksi baris nama wilayah ────────────────────────────────────
        if first_cell in REGIONS:
            # Simpan buffer wilayah sebelumnya
            if cur_region and header_cols and row_buffer:
                tmp = pd.DataFrame(row_buffer, columns=header_cols)
                tmp.insert(0, "region",     cur_region)
                tmp.insert(1, "actor_type", actor_type)
                collected.append(tmp)
            cur_region  = first_cell
            header_cols = None
            row_buffer  = []

        # ── Deteksi baris header (kolom pertama = 'dmu') ──────────────────
        elif first_cell.lower() == "dmu" and cur_region is not None:
            header_cols = [str(v).strip() for v in row if pd.notna(v)]

        # ── Deteksi baris data (kolom pertama berupa angka) ───────────────
        elif cur_region is not None and header_cols is not None:
            try:
                float(first_cell)
                vals = list(row)[: len(header_cols)]
                if len(vals) == len(header_cols):
                    row_buffer.append(vals)
            except (ValueError, TypeError):
                pass  # Abaikan baris kosong / komentar

    # Simpan wilayah terakhir di sheet
    if cur_region and header_cols and row_buffer:
        tmp = pd.DataFrame(row_buffer, columns=header_cols)
        tmp.insert(0, "region",     cur_region)
        tmp.insert(1, "actor_type", actor_type)
        collected.append(tmp)

    if not collected:
        print(f"  ⚠️  Sheet '{sheet_name}' tidak menghasilkan data.")
        return pd.DataFrame()

    result = pd.concat(collected, ignore_index=True)

    # Konversi semua kolom (kecuali region & actor_type) ke numerik
    skip = {"region", "actor_type"}
    for col in result.columns:
        if col not in skip:
            result[col] = pd.to_numeric(result[col], errors="coerce")

    return result



"""HASIL DATA AQUACITION"""

FILE_PATH = "data/data2.xlsx"

print("⏳ Memuat dan mem-parsing dataset …")

try:
    df_farmer     = parse_regional_sheet(FILE_PATH, "Farmer Data",      "Farmer")
    df_miller     = parse_regional_sheet(FILE_PATH, "Rice Miller Data", "Miller")
    df_middlemen  = parse_regional_sheet(FILE_PATH, "Middlemen Data",   "Middlemen")
    df_wholesaler = parse_regional_sheet(FILE_PATH, "Wholesaler Data",  "Wholesaler")
    df_retail     = parse_regional_sheet(FILE_PATH, "Retail Data",      "Retail")
    print("✅ Semua sheet berhasil di-parse")
except FileNotFoundError:
    print(f"❌ File tidak ditemukan: {FILE_PATH}")
    print("   → Upload file ke models/ lalu jalankan ulang cell ini")
    raise

SHEETS = {
    "Farmer":     df_farmer,
    "Miller":     df_miller,
    "Middlemen":  df_middlemen,
    "Wholesaler": df_wholesaler,
    "Retail":     df_retail,
}

# ── Ringkasan Dataset ─────────────────────────────────────────────────────
print("\n📊 RINGKASAN DATASET")
print(f"{'Aktor':<13} {'Total DMU':<11} {'Distribusi per Wilayah'}")
print("─" * 75)
for name, df in SHEETS.items():
    if df.empty:
        continue
    dist     = df["region"].value_counts().to_dict()
    dist_str = "  ".join(f"{r}:{c}" for r, c in dist.items())
    print(f"{name:<13} {len(df):<11} {dist_str}")

# ── Pivot table DMU per wilayah per aktor ────────────────────────────────
all_df = pd.concat(SHEETS.values(), ignore_index=True)
pivot  = pd.pivot_table(all_df, values="dmu",
                        index="region", columns="actor_type",
                        aggfunc="count", fill_value=0)
print("\n📋 Tabel Pivot: Jumlah DMU per Wilayah per Aktor")
print(pivot.to_string())

print("\n✅ [CELL 3] Data Acquisition selesai")

"""testing apakah memang karena datanya sudah bersih"""

for name, df in SHEETS.items():
    print(f"{name}: {df.isnull().sum().sum()} missing")

"""EDA ADALAH KOENTJI"""

print("=" * 65)
print("📋  INFO DASAR SETIAP SHEET")
print("=" * 65)
for name, df in SHEETS.items():
    if df.empty:
        continue
    mv = df.isnull().sum().sum()
    print(f"\n── {name} {'─'*(45-len(name))}")
    print(f"  Shape   : {df.shape[0]} baris × {df.shape[1]} kolom")
    print(f"  Missing : {mv} nilai kosong")
    num_df = df.select_dtypes(include="number")
    if not num_df.empty:
        desc = num_df.describe().T[["mean", "std", "min", "max"]].round(0)
        print(desc.to_string())

"""HEATMAP MISSING VALUE"""

fig, axes = plt.subplots(1, 5, figsize=(22, 4))
fig.suptitle("Heatmap Missing Values per Sheet", fontsize=14, fontweight="bold")
for ax, (name, df) in zip(axes, SHEETS.items()):
    if df.empty:
        ax.set_visible(False)
        continue
    sns.heatmap(df.isnull(), ax=ax, cbar=False, cmap="Reds", yticklabels=False)
    mv_count = df.isnull().sum().sum()
    ax.set_title(f"{name}\n({mv_count} missing)", fontsize=9, fontweight="bold")
    ax.set_xticklabels(ax.get_xticklabels(), rotation=90, fontsize=6)
plt.tight_layout()
plt.savefig("content/01_missing_values.png", dpi=100, bbox_inches="tight")
plt.show()
print("\n💡 Insight: Missing values relatif sedikit pada semua sheet.")
print("   Imputasi median per wilayah akan digunakan pada tahap Data Preparation.")

"""Distribusi Production Value per Wilayah"""

fig, axes = plt.subplots(1, 5, figsize=(20, 4))
fig.suptitle("Distribusi Nilai Produksi Petani per Wilayah (Juta IDR)",
             fontsize=13, fontweight="bold")
for ax, region, color in zip(axes, REGIONS, REGION_COLORS):
    sub = df_farmer[df_farmer["region"] == region]["Production value (IDR)"].dropna()
    if sub.empty:
        ax.set_visible(False)
        continue
    ax.hist(sub / 1e6, bins=15, color=color, edgecolor="white", alpha=0.85)
    ax.set_title(region, fontsize=10, fontweight="bold", color=color)
    ax.set_xlabel("Nilai Produksi\n(Juta IDR)", fontsize=8)
    ax.set_ylabel("Frekuensi", fontsize=8)
    ax.axvline(sub.median() / 1e6, color="black", linestyle="--",
               linewidth=1.2, label=f"Median")
    ax.legend(fontsize=7)
plt.tight_layout()
plt.savefig("content/02_dist_production.png", dpi=100, bbox_inches="tight")
plt.show()
print("\n💡 Insight: Distribusi nilai produksi bersifat right-skewed di semua wilayah.")
print("   Karawang dan Indramayu menunjukkan median lebih tinggi dibanding wilayah lain.")

"""Boxplot Nilai Produksi Antar Wilayah"""

fig, ax = plt.subplots(figsize=(12, 5))
data_box = [
    df_farmer[df_farmer["region"] == r]["Production value (IDR)"].dropna() / 1e6
    for r in REGIONS
]
bp = ax.boxplot(data_box, patch_artist=True, notch=False,
                medianprops=dict(color="black", linewidth=2))
for patch, color in zip(bp["boxes"], REGION_COLORS):
    patch.set_facecolor(color)
    patch.set_alpha(0.8)
ax.set_xticklabels(REGIONS, fontsize=11)
ax.set_xlabel("Wilayah", fontsize=11)
ax.set_ylabel("Nilai Produksi (Juta IDR)", fontsize=11)
ax.set_title("Perbandingan Nilai Produksi Petani Antar Wilayah",
             fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("content/03_boxplot_production.png", dpi=100, bbox_inches="tight")
plt.show()
print("\n💡 Insight: Karawang dan Indramayu memiliki median dan variasi produksi tertinggi.")
print("   Garut memiliki distribusi yang lebih sempit, mencerminkan lahan yang lebih homogen.")

"""Scatter: Land Area vs Production Value"""

fig, ax = plt.subplots(figsize=(11, 6))
for region, color in zip(REGIONS, REGION_COLORS):
    sub = df_farmer[df_farmer["region"] == region]
    ax.scatter(sub["Land area (m2)"] / 1e3,
               sub["Production value (IDR)"] / 1e6,
               c=color, label=region, alpha=0.55, s=30, edgecolors="none")
ax.set_xlabel("Luas Lahan (× 1.000 m²)", fontsize=11)
ax.set_ylabel("Nilai Produksi (Juta IDR)", fontsize=11)
ax.set_title("Luas Lahan vs Nilai Produksi per Wilayah", fontsize=13, fontweight="bold")
ax.legend(title="Wilayah", fontsize=9)
plt.tight_layout()
plt.savefig("content/04_scatter_area_prod.png", dpi=100, bbox_inches="tight")
plt.show()
print("\n💡 Insight: Hubungan positif kuat antara luas lahan dan nilai produksi.")
print("   Lahan lebih luas tidak selalu menjamin efisiensi optimal (terdapat outlier).")

"""Rata-rata Profit Margin per Aktor per Wilayah ( sudah dibersihkan di sini missing valuenya )"""

RETAIL_INPUTS = [
    "Value of rice purchase (IDR)",
    "Building rent cost (IDR)",
    "Labor cost (IDR)",
    "Supporting equipment cost (IDR)",
]

# Cek 5 baris Retail Garut
sample = df_retail[df_retail["region"] == "Garut"].copy()
avail  = [c for c in RETAIL_INPUTS if c in sample.columns]
sample["_total_input"] = sample[avail].sum(axis=1)
sample["_output"]      = sample["Value of rice sold (IDR)"]
sample["_margin"]      = (sample["_output"] - sample["_total_input"]) / sample["_output"] * 100

print(sample[["dmu", "_total_input", "_output", "_margin"]].head(10).round(0).to_string())

# Cek: apakah Value of rice purchase >> Value of rice sold?
print(f"\nRata-rata beli : {sample['Value of rice purchase (IDR)'].mean():,.0f}")
print(f"Rata-rata jual : {sample['Value of rice sold (IDR)'].mean():,.0f}")
print(f"Selisih rata2  : {(sample['Value of rice sold (IDR)'] - sample['Value of rice purchase (IDR)']).mean():,.0f}")

def gross_margin_trader(df, purchase_col, output_col, actor_name):
    """
    Gross margin: hanya harga jual vs harga beli beras.
    Tidak memasukkan overhead karena berbeda periode pengukuran.
    """
    d = df.copy()
    d.columns = [c.strip() for c in d.columns]

    if purchase_col not in d.columns or output_col not in d.columns:
        print(f"⚠️  [{actor_name}] Kolom tidak ditemukan!")
        return pd.Series([np.nan]*len(REGIONS), index=REGIONS)

    d["_gross_margin"] = (
        (d[output_col] - d[purchase_col])
        / d[output_col].replace(0, np.nan) * 100
    )
    result = d.groupby("region")["_gross_margin"].mean().reindex(REGIONS)

    print(f"\n✅ [{actor_name}] Gross Margin per wilayah:")
    for region, val in result.items():
        if not np.isnan(val):
            status = "✅" if val > 0 else "❌"
            print(f"   {region:<12}: {val:6.1f}%  {status}")
    return result


# Hitung ulang dengan metode yang benar
print("=" * 55)
print("📊 GROSS MARGIN TRADER (Metode yang Benar)")
print("=" * 55)

gross_df = pd.DataFrame({
    "Middlemen":  gross_margin_trader(df_middlemen,  "Total rice purchase (IDR)",    "Value of rice sold (IDR)", "Middlemen"),
    "Wholesaler": gross_margin_trader(df_wholesaler, "Value of rice purchase (IDR)", "Value of rice sold (IDR)", "Wholesaler"),
    "Retail":     gross_margin_trader(df_retail,     "Value of rice purchase (IDR)", "Value of rice sold (IDR)", "Retail"),
})

# Visualisasi gross margin yang bersih
fig, ax = plt.subplots(figsize=(12, 5))
x     = np.arange(len(REGIONS))
width = 0.25

for i, (actor, color) in enumerate(zip(
    ["Middlemen","Wholesaler","Retail"],
    ["#F18F01",  "#C73E1D",   "#3B1F2B"]
)):
    vals = gross_df[actor]
    ax.bar(x + (i-1)*width, vals.fillna(0), width,
           label=actor, color=color, edgecolor="white", alpha=0.85)
    # Label nilai di atas bar
    for xi, val in zip(x + (i-1)*width, vals):
        if not np.isnan(val):
            ax.text(xi, val + 0.2, f"{val:.1f}%",
                    ha="center", va="bottom", fontsize=7, fontweight="bold")

ax.axhline(0, color="black", linewidth=0.8, linestyle="--")
ax.set_xticks(x)
ax.set_xticklabels(REGIONS, fontsize=10)
ax.set_ylabel("Gross Margin (%)", fontsize=11)
ax.set_title("Gross Margin Pedagang per Wilayah\n(Selisih Harga Jual vs Harga Beli Beras)",
             fontsize=12, fontweight="bold")
ax.legend(title="Aktor", fontsize=9)
plt.tight_layout()
plt.savefig("content/05_gross_margin_fixed.png", dpi=100, bbox_inches="tight")
plt.show()

print("\n💡 Insight yang valid:")
print("   Gross margin pedagang berkisar 5-25% — wajar untuk rantai pasok beras.")
print("   Overhead tinggi menunjukkan skala usaha kecil dengan fixed cost tidak efisien.")

"""Heatmap Korelasi Farmer Data"""

num_cols = [c for c in df_farmer.columns if c not in {"region", "actor_type", "dmu"}]
corr     = df_farmer[num_cols].corr()
fig, ax  = plt.subplots(figsize=(11, 7))
mask     = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt=".2f",
            cmap="coolwarm", vmin=-1, vmax=1, ax=ax,
            linewidths=0.3, annot_kws={"size": 7})
ax.set_title("Heatmap Korelasi — Farmer Data", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("content/06_correlation.png", dpi=100, bbox_inches="tight")
plt.show()
print("\n💡 Insight: Luas lahan berkorelasi sangat kuat dengan semua biaya input dan output.")
print("   Biaya pupuk dan biaya tenaga kerja memiliki korelasi paling tinggi terhadap nilai produksi.")

"""Bar: Total Produksi per Wilayah & Pie: Jumlah DMU"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

prod_by_region = df_farmer.groupby("region")["Production value (IDR)"].sum().reindex(REGIONS) / 1e9
bars = ax1.bar(REGIONS, prod_by_region, color=REGION_COLORS, edgecolor="white", alpha=0.85)
for bar, val in zip(bars, prod_by_region):
    ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
             f"{val:.1f}B", ha="center", va="bottom", fontsize=9, fontweight="bold")
ax1.set_ylabel("Total Nilai Produksi (Miliar IDR)", fontsize=11)
ax1.set_title("Total Nilai Produksi Petani per Wilayah", fontsize=12, fontweight="bold")
ax1.set_xticklabels(REGIONS, rotation=15, fontsize=10)

dmu_count = df_farmer["region"].value_counts().reindex(REGIONS)
ax2.pie(dmu_count, labels=REGIONS, colors=REGION_COLORS,
        autopct="%1.1f%%", startangle=140, pctdistance=0.8,
        textprops={"fontsize": 9})
ax2.set_title("Distribusi Jumlah DMU Petani per Wilayah", fontsize=12, fontweight="bold")

plt.tight_layout()
plt.savefig("content/07_regional_analysis.png", dpi=100, bbox_inches="tight")
plt.show()
print("\n💡 Insight: Tasikmalaya memiliki jumlah petani (DMU) terbanyak, namun total nilai")
print("   produksinya tidak proporsional — menandakan produktivitas per DMU yang lebih rendah.")

print("\n✅ [CELL 4] Data Understanding selesai")

"""DATA PREPARATION  """

def impute_median_region(df: pd.DataFrame) -> pd.DataFrame:
    """Imputasi nilai kosong dengan median per wilayah."""
    df = df.copy()
    num_cols = df.select_dtypes(include="number").columns.tolist()
    for col in num_cols:
        df[col] = df.groupby("region")[col].transform(
            lambda x: x.fillna(x.median())
        )
    return df

df_farmer     = impute_median_region(df_farmer)
df_miller     = impute_median_region(df_miller)
df_middlemen  = impute_median_region(df_middlemen)
df_wholesaler = impute_median_region(df_wholesaler)
df_retail     = impute_median_region(df_retail)

remaining = sum(df.isnull().sum().sum() for df in SHEETS.values())
print(f"✅ Imputasi selesai. Total missing value tersisa: {remaining}")

# ── 5.2 Penanganan Outlier (IQR Capping) ──────────────────────────────────
def cap_outliers_iqr(df: pd.DataFrame, cols: list) -> pd.DataFrame:
    """Capping outlier pada batas IQR 1.5× (tidak dihapus)."""
    df = df.copy()
    report = {}
    for col in cols:
        Q1  = df[col].quantile(0.25)
        Q3  = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lo  = Q1 - 1.5 * IQR
        hi  = Q3 + 1.5 * IQR
        n_before = ((df[col] < lo) | (df[col] > hi)).sum()
        df[col]  = df[col].clip(lower=lo, upper=hi)
        report[col] = n_before
    n_total = sum(report.values())
    print(f"  → {n_total} nilai di-cap pada kolom: "
          f"{[k for k, v in report.items() if v > 0]}")
    return df

farmer_num = [c for c in df_farmer.columns if c not in {"region", "actor_type", "dmu"}]
print("⏳ Capping outlier Farmer Data …")
df_farmer = cap_outliers_iqr(df_farmer, farmer_num)

# Visualisasi sebelum & sesudah (2 kolom contoh)
sample_cols = ["Production value (IDR)", "Fertilizer purchase value (IDR)"]
df_farmer_before_cap = impute_median_region(
    parse_regional_sheet(FILE_PATH, "Farmer Data", "Farmer")
)
fig, axes = plt.subplots(2, 2, figsize=(14, 7))
fig.suptitle("Outlier Capping — Sebelum vs Sesudah (Farmer Data)",
             fontsize=13, fontweight="bold")
for row_idx, col in enumerate(sample_cols):
    for col_idx, (data, label) in enumerate([
        (df_farmer_before_cap[col] / 1e6, "Sebelum"),
        (df_farmer[col] / 1e6,            "Sesudah"),
    ]):
        ax = axes[row_idx][col_idx]
        ax.boxplot(data.dropna(), patch_artist=True,
                   boxprops=dict(facecolor=REGION_COLORS[col_idx * 2], alpha=0.7))
        ax.set_title(f"{col.split('(')[0].strip()}\n{label}", fontsize=9)
        ax.set_ylabel("Juta IDR", fontsize=8)
plt.tight_layout()
plt.savefig("content/08_outlier_capping.png", dpi=100, bbox_inches="tight")
plt.show()
print("✅ Outlier Farmer Data berhasil di-cap")

# ── 5.3 Feature Engineering ───────────────────────────────────────────────
FARMER_INPUTS = [
    "Land lease value (IDR)",
    "Labor cost (IDR)",
    "Seed purchase value (IDR)",
    "Fertilizer purchase value (IDR)",
    "Pesticide purchase value (IDR)",
    "Equipment rent value (IDR)",
]

# Farmer Data
df_farmer["total_input_cost"]   = df_farmer[FARMER_INPUTS].sum(axis=1)
df_farmer["profit"]             = df_farmer["Production value (IDR)"] - df_farmer["total_input_cost"]
df_farmer["profit_margin_pct"]  = (df_farmer["profit"]
                                   / df_farmer["Production value (IDR)"].replace(0, np.nan) * 100)
df_farmer["cost_per_m2"]        = (df_farmer["total_input_cost"]
                                   / df_farmer["Land area (m2)"].replace(0, np.nan))
df_farmer["revenue_per_m2"]     = (df_farmer["Production value (IDR)"]
                                   / df_farmer["Land area (m2)"].replace(0, np.nan))
df_farmer["fertilizer_ratio"]   = (df_farmer["Fertilizer purchase value (IDR)"]
                                   / df_farmer["total_input_cost"].replace(0, np.nan))
df_farmer["labor_ratio"]        = (df_farmer["Labor cost (IDR)"]
                                   / df_farmer["total_input_cost"].replace(0, np.nan))
print("✅ Feature engineering Farmer Data selesai")

# Miller, Middlemen, Wholesaler, Retail
MILLER_INPUTS = [
    "Value of milled grains (IDR)",
    "Labor cost (IDR)",
    "Supporting equipment cost (IDR)",
]
MIDDLEMEN_INPUTS = [
    "Total rice purchase (IDR)",
    "Building rent cost (IDR)",
    "Labor cost (IDR)",
    "Supporting equipment cost (IDR)",
]
WHOLESALER_INPUTS = [
    "Value of rice purchase (IDR)",
    "Building rent cost (IDR)",
    "Labor cost (IDR)",
    "Supporting equipment cost (IDR)",
]
RETAIL_INPUTS = [
    "Value of rice purchase (IDR)",
    "Building rent cost (IDR)",
    "Labor cost (IDR)",
    "Supporting equipment cost (IDR)",
]

for df, inp_cols, out_col in [
    (df_miller,     MILLER_INPUTS,     "Total revenue of milling machine (IDR)"),
    (df_middlemen,  MIDDLEMEN_INPUTS,  "Value of rice sold (IDR)"),
    (df_wholesaler, WHOLESALER_INPUTS, "Value of rice sold (IDR)"),
    (df_retail,     RETAIL_INPUTS,     "Value of rice sold (IDR)"),
]:
    avail = [c for c in inp_cols if c in df.columns]
    df["total_input_cost"]  = df[avail].sum(axis=1)
    df["profit"]            = df[out_col] - df["total_input_cost"]
    df["profit_margin_pct"] = (df["profit"]
                               / df[out_col].replace(0, np.nan) * 100)
    df["cost_efficiency"]   = (df[out_col]
                               / df["total_input_cost"].replace(0, np.nan))
print("✅ Feature engineering Miller/Middlemen/Wholesaler/Retail selesai")

# Tambahkan cost_efficiency juga ke Farmer
df_farmer["cost_efficiency"] = (
    df_farmer["Production value (IDR)"]
    / df_farmer["total_input_cost"].replace(0, np.nan)
)

# ── 5.4 Label Encoding Wilayah ────────────────────────────────────────────
le = LabelEncoder()
le.fit(REGIONS)
region_map = dict(zip(le.classes_, le.transform(le.classes_)))

for df in [df_farmer, df_miller, df_middlemen, df_wholesaler, df_retail]:
    df["region_encoded"] = df["region"].map(region_map).fillna(-1).astype(int)

print(f"✅ Label encoding wilayah: {region_map}")

# ── 5.5 Scaler untuk DEA dan ML ───────────────────────────────────────────
DEA_INPUT_COLS  = ["Land area (m2)", "total_input_cost"]
DEA_OUTPUT_COLS = ["Production value (IDR)"]

RF_FEATURE_COLS = [
    "Land area (m2)", "Land lease value (IDR)", "Labor cost (IDR)",
    "Seed purchase value (IDR)", "Fertilizer purchase value (IDR)",
    "Pesticide purchase value (IDR)", "Equipment rent value (IDR)",
    "region_encoded", "cost_per_m2", "fertilizer_ratio", "labor_ratio",
]
RF_TARGET_COL = "Production value (IDR)"

scaler_dea = MinMaxScaler()
scaler_rf  = StandardScaler()

df_dea_prep = df_farmer[DEA_INPUT_COLS + DEA_OUTPUT_COLS].dropna().copy()
scaler_dea.fit(df_dea_prep[DEA_INPUT_COLS])

df_rf_prep = df_farmer[RF_FEATURE_COLS + [RF_TARGET_COL]].dropna().copy()
scaler_rf.fit(df_rf_prep[RF_FEATURE_COLS])

joblib.dump(scaler_dea, "models/scaler_dea.pkl")
joblib.dump(scaler_rf,  "models/scaler_rf.pkl")
print(f"✅ Scaler DEA & RF disimpan ke models/")

print("\n✅ [CELL 5] Data Preparation selesai")

"""MODELING ( DEA )"""

def run_dea_ccr(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    """
    CCR Input-Oriented DEA menggunakan scipy.optimize.linprog.

    Parameters
    ----------
    X : ndarray (n, m)  — matrix input  (n DMU, m variabel input)
    Y : ndarray (n, s)  — matrix output (n DMU, s variabel output)

    Returns
    -------
    scores : ndarray (n,)  — skor efisiensi [0, 1]
    """
    n, m = X.shape
    s    = Y.shape[1]
    scores = []

    for k in range(n):
        # Variabel optimasi: [θ, λ_0, λ_1, …, λ_{n-1}]
        c = np.zeros(n + 1)
        c[0] = 1.0   # minimize θ

        # Constraint input: -X[k,i]·θ + Σ X[j,i]·λ_j ≤ 0
        A_in = np.zeros((m, n + 1))
        b_in = np.zeros(m)
        for i in range(m):
            A_in[i, 0]  = -X[k, i]     # koefisien θ
            A_in[i, 1:] =  X[:, i]     # koefisien λ

        # Constraint output: -Σ Y[j,r]·λ_j ≤ -Y[k,r]
        A_out = np.zeros((s, n + 1))
        b_out = -Y[k, :]
        for r in range(s):
            A_out[r, 1:] = -Y[:, r]    # koefisien λ

        A_ub = np.vstack([A_in,  A_out])
        b_ub = np.hstack([b_in,  b_out])
        bounds = [(0, None)] * (n + 1)

        res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method="highs")
        scores.append(float(np.clip(res.fun, 0, 1)) if res.success else np.nan)

    return np.array(scores)

"""Menjalankan DEA per Wilayah"""

print("⏳ Menjalankan DEA per wilayah …")
dea_by_region = {}

for region in REGIONS:
    sub = df_farmer[df_farmer["region"] == region].copy()
    if sub.empty:
        continue
    sub_clean = sub[DEA_INPUT_COLS + DEA_OUTPUT_COLS].dropna()
    if len(sub_clean) < 3:
        continue

    X_raw = sub_clean[DEA_INPUT_COLS].values.astype(float)
    Y_raw = sub_clean[DEA_OUTPUT_COLS].values.astype(float)

    # Normalisasi per wilayah agar skala seimbang
    X_norm = X_raw / (X_raw.max(axis=0) + 1e-9)
    Y_norm = Y_raw / (Y_raw.max(axis=0) + 1e-9)

    scores = run_dea_ccr(X_norm, Y_norm)
    sub_clean = sub_clean.copy()
    sub_clean["dea_score"] = scores
    sub_clean["region"]    = region
    dea_by_region[region]  = sub_clean

    eff_pct = np.mean(scores >= 0.9) * 100
    print(f"  {region:<12}: n={len(sub_clean):3d} | "
          f"μ={np.nanmean(scores):.3f} | Efisien(≥0.9): {eff_pct:.1f}%")

df_dea_all = pd.concat(dea_by_region.values(), ignore_index=True)
joblib.dump(dea_by_region, "models/dea_results.pkl")
print("✅ DEA selesai & disimpan")

# Visualisasi DEA
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle("Hasil DEA — Efisiensi Petani per Wilayah",
             fontsize=14, fontweight="bold")

ax = axes[0]
for region, color in zip(REGIONS, REGION_COLORS):
    if region not in dea_by_region:
        continue
    scores = dea_by_region[region]["dea_score"].dropna()
    ax.hist(scores, bins=10, alpha=0.55, color=color, label=region, edgecolor="white")
ax.axvline(0.9, color="red", linestyle="--", linewidth=1.5, label="Threshold 0.9")
ax.set_xlabel("DEA Efficiency Score", fontsize=11)
ax.set_ylabel("Jumlah Petani (DMU)", fontsize=11)
ax.set_title("Distribusi Skor Efisiensi per Wilayah", fontsize=12, fontweight="bold")
ax.legend(fontsize=9)

ax2 = axes[1]
eff_pct_dict = {
    r: np.mean(dea_by_region[r]["dea_score"].dropna() >= 0.9) * 100
    for r in REGIONS if r in dea_by_region
}
bars = ax2.bar(list(eff_pct_dict.keys()), list(eff_pct_dict.values()),
               color=REGION_COLORS[:len(eff_pct_dict)],
               edgecolor="white", alpha=0.85)
for bar, val in zip(bars, eff_pct_dict.values()):
    ax2.text(bar.get_x() + bar.get_width() / 2,
             bar.get_height() + 0.5,
             f"{val:.1f}%", ha="center", va="bottom",
             fontsize=10, fontweight="bold")
ax2.set_ylabel("% DMU Efisien (Score ≥ 0.9)", fontsize=11)
ax2.set_title("Persentase Petani Efisien per Wilayah", fontsize=12, fontweight="bold")
ax2.set_ylim(0, 108)
plt.tight_layout()
plt.savefig("content/09_dea_results.png", dpi=100, bbox_inches="tight")
plt.show()
print("💡 Insight: Karawang & Indramayu mencatat persentase petani efisien tertinggi.")

# Top 5 & Bottom 5 per wilayah
print("\n📊 Top 5 & Bottom 5 DMU per Wilayah (DEA Score):")
for region in REGIONS:
    if region not in dea_by_region:
        continue
    sub = dea_by_region[region].sort_values("dea_score", ascending=False)
    show_cols = ["dmu", "dea_score", "Land area (m2)", "Production value (IDR)"]
    show_cols = [c for c in show_cols if c in sub.columns]
    print(f"\n  ── {region} ──────────────────")
    print("  TOP 5:")
    print(sub[show_cols].head(5).round(3).to_string(index=False))
    print("  BOTTOM 5:")
    print(sub[show_cols].tail(5).round(3).to_string(index=False))

print("\n✅ Model A (DEA) selesai")

"""MODELING ( RANDOM FOREST )"""

df_rf  = df_farmer[RF_FEATURE_COLS + [RF_TARGET_COL]].dropna().copy()
X_all  = df_rf[RF_FEATURE_COLS].values
y_all  = df_rf[RF_TARGET_COL].values

# Stratified split berdasarkan wilayah
X_train, X_test, y_train, y_test = train_test_split(
    X_all, y_all, test_size=0.2, random_state=RANDOM_STATE
)

X_train_sc = scaler_rf.transform(X_train)
X_test_sc  = scaler_rf.transform(X_test)
print(f"✅ Split data: Train={len(X_train)} | Test={len(X_test)}")

# GridSearchCV
print("⏳ GridSearchCV sedang berjalan …")
param_grid = {
    "n_estimators":      [100, 200],
    "max_depth":         [None, 10, 20],
    "min_samples_split": [2, 5],
}
grid = GridSearchCV(
    RandomForestRegressor(random_state=RANDOM_STATE, n_jobs=-1),
    param_grid, cv=5, scoring="r2", n_jobs=-1, verbose=0
)
grid.fit(X_train_sc, y_train)
print(f"✅ Best params : {grid.best_params_}")
print(f"   CV R² terbaik : {grid.best_score_:.4f}")

rf_model = grid.best_estimator_
joblib.dump(rf_model, "models/rf_farmer_model.pkl")
print("✅ Model RF disimpan: models/rf_farmer_model.pkl")

"""VISUALISASI LEARNING CURVE"""

# Learning Curve
train_sizes, tr_sc, val_sc = learning_curve(
    rf_model, X_train_sc, y_train,
    cv=5, train_sizes=np.linspace(0.1, 1.0, 8),
    scoring="r2", n_jobs=-1
)
fig, ax = plt.subplots(figsize=(9, 4))
ax.plot(train_sizes, tr_sc.mean(axis=1),  "o-", color="#2E86AB", label="Train R²")
ax.fill_between(train_sizes,
                tr_sc.mean(axis=1) - tr_sc.std(axis=1),
                tr_sc.mean(axis=1) + tr_sc.std(axis=1),
                alpha=0.15, color="#2E86AB")
ax.plot(train_sizes, val_sc.mean(axis=1), "o-", color="#C73E1D", label="Validation R²")
ax.fill_between(train_sizes,
                val_sc.mean(axis=1) - val_sc.std(axis=1),
                val_sc.mean(axis=1) + val_sc.std(axis=1),
                alpha=0.15, color="#C73E1D")
ax.set_xlabel("Ukuran Training Set", fontsize=11)
ax.set_ylabel("R² Score", fontsize=11)
ax.set_title("Learning Curve — Random Forest Regression", fontsize=12, fontweight="bold")
ax.legend(fontsize=10)
ax.set_ylim(-0.05, 1.05)
plt.tight_layout()
plt.savefig("content/10_learning_curve.png", dpi=100, bbox_inches="tight")
plt.show()

"""VISUALISASI FEATURE CURVE"""

feat_imp = pd.Series(rf_model.feature_importances_,
                     index=RF_FEATURE_COLS).sort_values()
fig, ax = plt.subplots(figsize=(9, 5))
colors_imp = [REGION_COLORS[min(i, 4)] for i in range(len(feat_imp))]
bars = ax.barh(feat_imp.index, feat_imp.values,
               color="#2E86AB", edgecolor="white", alpha=0.85)
for bar, val in zip(bars, feat_imp.values):
    ax.text(val + 0.002, bar.get_y() + bar.get_height() / 2,
            f"{val:.3f}", va="center", fontsize=8)
ax.set_xlabel("Feature Importance (Mean Decrease Impurity)", fontsize=11)
ax.set_title("Feature Importance — Random Forest (Farmer Data)",
             fontsize=12, fontweight="bold")
plt.tight_layout()
plt.savefig("content/11_feature_importance.png", dpi=100, bbox_inches="tight")
plt.show()
print("💡 Insight: Land area dan total_input_cost mendominasi prediksi nilai produksi.")

print("\n✅ Model B (Random Forest) selesai")

"""MODELING ( ISOLATION FOREST )"""

SHEETS = {
    "Farmer":     df_farmer,
    "Miller":     df_miller,
    "Middlemen":  df_middlemen,
    "Wholesaler": df_wholesaler,
    "Retail":     df_retail,
}

dfs_anomaly = []
for name, df in SHEETS.items():
    if df.empty or "profit_margin_pct" not in df.columns:
        continue
    tmp = df[["region", "actor_type", "profit_margin_pct",
              "cost_efficiency", "total_input_cost"]].copy()
    dfs_anomaly.append(tmp)

df_iso = pd.concat(dfs_anomaly, ignore_index=True).dropna()
print(f"Data Isolation Forest: {len(df_iso)} baris dari semua aktor")

ISO_FEATURES = ["profit_margin_pct", "cost_efficiency"]
X_iso        = df_iso[ISO_FEATURES].values

scaler_iso  = StandardScaler()
X_iso_sc    = scaler_iso.fit_transform(X_iso)

iso_model   = IsolationForest(contamination=0.10, random_state=RANDOM_STATE)
labels      = iso_model.fit_predict(X_iso_sc)   # 1=normal, -1=anomali

df_iso["anomaly"]       = labels
df_iso["anomaly_label"] = df_iso["anomaly"].map({1: "Normal", -1: "Anomali"})

joblib.dump(iso_model,  "models/iso_model.pkl")
joblib.dump(scaler_iso, "models/scaler_iso.pkl")
print("✅ Isolation Forest selesai & disimpan")

# Visualisasi Anomali
fig, axes = plt.subplots(1, 2, figsize=(15, 5))
fig.suptitle("Deteksi Anomali — Isolation Forest", fontsize=13, fontweight="bold")

ax = axes[0]
color_map = {"Normal": "#2E86AB", "Anomali": "#C73E1D"}
for label, grp in df_iso.groupby("anomaly_label"):
    ax.scatter(grp["profit_margin_pct"], grp["cost_efficiency"],
               c=color_map[label], label=label, alpha=0.55, s=25, edgecolors="none")
ax.set_xlabel("Profit Margin (%)", fontsize=11)
ax.set_ylabel("Cost Efficiency Ratio", fontsize=11)
ax.set_title("Profit Margin vs Cost Efficiency", fontsize=11, fontweight="bold")
ax.legend(fontsize=10)

ax2 = axes[1]
anom_pct = df_iso.groupby("actor_type").apply(
    lambda g: (g["anomaly"] == -1).mean() * 100
)
actor_order = ["Farmer", "Miller", "Middlemen", "Wholesaler", "Retail"]
anom_pct = anom_pct.reindex([a for a in actor_order if a in anom_pct.index])
bars = ax2.bar(anom_pct.index, anom_pct.values,
               color=REGION_COLORS[:len(anom_pct)],
               edgecolor="white", alpha=0.85)
for bar, val in zip(bars, anom_pct.values):
    ax2.text(bar.get_x() + bar.get_width() / 2,
             bar.get_height() + 0.2,
             f"{val:.1f}%", ha="center", va="bottom",
             fontsize=9, fontweight="bold")
ax2.set_ylabel("% DMU Anomali", fontsize=11)
ax2.set_title("Persentase Anomali per Aktor", fontsize=11, fontweight="bold")
ax2.set_ylim(0, 25)
plt.tight_layout()
plt.savefig("content/12_anomaly.png", dpi=100, bbox_inches="tight")
plt.show()

# Tabel ringkasan anomali
print("\n📊 Tabel Ringkasan Anomali per Wilayah per Aktor:")
anom_table = df_iso.groupby(["region", "actor_type"]).apply(
    lambda g: pd.Series({
        "Total DMU": len(g),
        "Anomali (#)": (g["anomaly"] == -1).sum(),
        "Anomali (%)": f"{(g['anomaly'] == -1).mean() * 100:.1f}%",
    })
).reset_index()
print(anom_table.to_string(index=False))
print("💡 Insight: Middlemen menunjukkan persentase anomali tertinggi di hampir semua wilayah.")

print("\n✅ [CELL 6] Semua Model selesai")

"""EVALUATION"""

y_pred_train = rf_model.predict(X_train_sc)
y_pred_test  = rf_model.predict(X_test_sc)

def mape_score(y_true, y_pred):
    """Mean Absolute Percentage Error — abaikan y_true = 0."""
    mask = y_true != 0
    return np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100

metrics_table = pd.DataFrame({
    "Set":  ["Train",       "Test"],
    "MAE":  [mean_absolute_error(y_train, y_pred_train),
             mean_absolute_error(y_test,  y_pred_test)],
    "RMSE": [np.sqrt(mean_squared_error(y_train, y_pred_train)),
             np.sqrt(mean_squared_error(y_test,  y_pred_test))],
    "MAPE (%)": [mape_score(y_train, y_pred_train),
                 mape_score(y_test,  y_pred_test)],
    "R²":   [r2_score(y_train, y_pred_train),
             r2_score(y_test,  y_pred_test)],
}).set_index("Set")

print("\n📊 Tabel Evaluasi — Random Forest Regression:")
print(metrics_table.round(4).to_string())

"""VISUALISASI DEA ;v"""

# ── 7.2 Visualisasi Evaluasi ──────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Evaluasi Model Random Forest Regression",
             fontsize=13, fontweight="bold")

# (1) Actual vs Predicted
ax = axes[0]
ax.scatter(y_test / 1e6, y_pred_test / 1e6,
           alpha=0.5, color="#2E86AB", s=25, edgecolors="none")
lo = min(y_test.min(), y_pred_test.min()) / 1e6
hi = max(y_test.max(), y_pred_test.max()) / 1e6
ax.plot([lo, hi], [lo, hi], "r--", linewidth=1.5, label="y = x (ideal)")
ax.set_xlabel("Actual (Juta IDR)", fontsize=10)
ax.set_ylabel("Predicted (Juta IDR)", fontsize=10)
ax.set_title(f"Actual vs Predicted\nTest R² = {r2_score(y_test, y_pred_test):.4f}",
             fontsize=11, fontweight="bold")
ax.legend(fontsize=9)

# (2) Residual Plot
residuals = y_test - y_pred_test
ax2 = axes[1]
ax2.scatter(y_pred_test / 1e6, residuals / 1e6,
            alpha=0.5, color="#A23B72", s=25, edgecolors="none")
ax2.axhline(0, color="black", linestyle="--", linewidth=1)
ax2.set_xlabel("Predicted (Juta IDR)", fontsize=10)
ax2.set_ylabel("Residual (Juta IDR)", fontsize=10)
ax2.set_title("Residual Plot", fontsize=11, fontweight="bold")

# (3) Distribusi Residual
ax3 = axes[2]
ax3.hist(residuals / 1e6, bins=20, color="#F18F01", edgecolor="white", alpha=0.85)
ax3.axvline(0, color="black", linestyle="--", linewidth=1)
ax3.set_xlabel("Residual (Juta IDR)", fontsize=10)
ax3.set_ylabel("Frekuensi", fontsize=10)
ax3.set_title("Distribusi Residual", fontsize=11, fontweight="bold")

plt.tight_layout()
plt.savefig("content/13_rf_evaluation.png", dpi=100, bbox_inches="tight")
plt.show()
print("💡 Insight: Sebaran residual mendekati normal dan residual plot tidak menunjukkan")
print("   pola sistematis, mengindikasikan model cukup baik dan tidak ada bias struktural.")

"""EVALUASI DEA"""

print("\n📊 Statistik Skor DEA per Wilayah:")
dea_stats = df_dea_all.groupby("region")["dea_score"].agg(
    Mean="mean", Std="std", Min="min", Max="max",
    Efisien_pct=lambda x: (x >= 0.9).mean() * 100
).round(3)
print(dea_stats.to_string())

fig, ax = plt.subplots(figsize=(9, 4))
ax.hist(df_dea_all["dea_score"].dropna(), bins=20,
        color="#2E86AB", edgecolor="white", alpha=0.85)
ax.axvline(df_dea_all["dea_score"].mean(), color="red",
           linestyle="--", linewidth=1.5,
           label=f"Mean = {df_dea_all['dea_score'].mean():.3f}")
ax.set_xlabel("DEA Efficiency Score", fontsize=11)
ax.set_ylabel("Jumlah Petani", fontsize=11)
ax.set_title("Distribusi Keseluruhan Skor Efisiensi DEA",
             fontsize=12, fontweight="bold")
ax.legend(fontsize=10)
plt.tight_layout()
plt.savefig("content/14_dea_dist.png", dpi=100, bbox_inches="tight")
plt.show()

"""SHAP Explainability"""

# ── 7.4 SHAP Explainability ───────────────────────────────────────────────
print("\n⏳ Menghitung SHAP values (mungkin 1 menit) …")

explainer = shap.TreeExplainer(rf_model)
shap_vals = explainer.shap_values(X_test_sc)

# Summary beeswarm
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_vals, X_test_sc,
                  feature_names=RF_FEATURE_COLS, show=False)
plt.title("SHAP Summary Plot (Beeswarm) — Random Forest",
          fontsize=12, fontweight="bold")
plt.tight_layout()
plt.savefig("content/15_shap_beeswarm.png", dpi=100, bbox_inches="tight")
plt.show()

# Bar plot mean |SHAP|
plt.figure(figsize=(9, 5))
shap.summary_plot(shap_vals, X_test_sc,
                  feature_names=RF_FEATURE_COLS,
                  plot_type="bar", show=False)
plt.title("SHAP — Mean |SHAP Value| per Fitur",
          fontsize=12, fontweight="bold")
plt.tight_layout()
plt.savefig("content/16_shap_bar.png", dpi=100, bbox_inches="tight")
plt.show()

# Waterfall untuk satu contoh
idx_sample = 0

base_value = explainer.expected_value
if isinstance(base_value, (list, np.ndarray)):
    base_value = np.array(base_value).flatten()[0]

shap_exp = shap.Explanation(
    values        = shap_vals[idx_sample],
    # base_values   = explainer.expected_value,
    base_values   = base_value,
    data          = X_test_sc[idx_sample],
    feature_names = RF_FEATURE_COLS,
)
plt.figure(figsize=(10, 5))
shap.plots.waterfall(shap_exp, show=False)
plt.title(f"SHAP Waterfall — Contoh Prediksi Ke-{idx_sample+1}",
          fontsize=12, fontweight="bold")
plt.tight_layout()
plt.savefig("content/17_shap_waterfall.png", dpi=100, bbox_inches="tight")
plt.show()
print("💡 Insight: SHAP mengkonfirmasi land area dan total biaya input sebagai")
print("   driver utama prediksi. Region_encoded juga berkontribusi signifikan.")

print("\n✅ [CELL 7] Evaluation & SHAP selesai")

"""

```
# IMPLEMENTASI
```

"""

_rf_model  = joblib.load("models/rf_farmer_model.pkl")
_scaler_rf = joblib.load("models/scaler_rf.pkl")


# ── 8.1 Fungsi Prediksi Tunggal ───────────────────────────────────────────
def predict_farmer_production(
    land_area_m2    : float,
    land_lease_value: float,
    labor_cost      : float,
    seed_value      : float,
    fertilizer_value: float,
    pesticide_value : float,
    equipment_rent  : float,
    region          : str,
) -> dict:
    """
    Pipeline inferensi lengkap untuk satu petani.

    Langkah:
    1. Validasi input
    2. Feature engineering otomatis (sama seperti training)
    3. Encoding wilayah
    4. StandardScaler transform
    5. Prediksi dengan Random Forest
    6. Hitung turunan: profit, margin, efisiensi
    7. Generate rekomendasi berbasis feature importance

    Parameters
    ----------
    land_area_m2     : Luas lahan (m²)
    land_lease_value : Biaya sewa lahan (IDR)
    labor_cost       : Biaya tenaga kerja (IDR)
    seed_value       : Biaya benih (IDR)
    fertilizer_value : Biaya pupuk (IDR)
    pesticide_value  : Biaya pestisida (IDR)
    equipment_rent   : Biaya sewa alat (IDR)
    region           : Nama wilayah

    Returns
    -------
    dict berisi prediksi, profit, margin, kategori efisiensi, rekomendasi
    """
    # Validasi
    if region not in REGIONS:
        raise ValueError(f"Wilayah tidak valid. Pilih dari: {REGIONS}")
    for nama, val in [("land_area_m2", land_area_m2),
                      ("land_lease_value", land_lease_value),
                      ("labor_cost", labor_cost)]:
        if val <= 0:
            raise ValueError(f"{nama} harus bernilai positif (> 0).")

    # Feature engineering
    total_input = (land_lease_value + labor_cost + seed_value
                   + fertilizer_value + pesticide_value + equipment_rent)
    cost_per_m2      = total_input / land_area_m2 if land_area_m2 > 0 else 0.0
    fertilizer_ratio = fertilizer_value / total_input if total_input > 0 else 0.0
    labor_ratio      = labor_cost / total_input if total_input > 0 else 0.0
    region_enc       = region_map.get(region, 0)

    features = np.array([[
        land_area_m2, land_lease_value, labor_cost,
        seed_value, fertilizer_value, pesticide_value, equipment_rent,
        region_enc, cost_per_m2, fertilizer_ratio, labor_ratio
    ]])
    features_sc = _scaler_rf.transform(features)

    # Prediksi
    pred_val    = float(_rf_model.predict(features_sc)[0])
    profit      = pred_val - total_input
    margin_pct  = (profit / pred_val * 100) if pred_val > 0 else 0.0
    rev_per_m2  = pred_val / land_area_m2 if land_area_m2 > 0 else 0.0

    # Kategori efisiensi
    if margin_pct >= 50:
        eff_cat = "🟢 Tinggi (>50%)"
    elif margin_pct >= 25:
        eff_cat = "🟡 Sedang (25–50%)"
    else:
        eff_cat = "🔴 Rendah (<25%)"

    # Rekomendasi berbasis feature importance
    recs = []
    if fertilizer_ratio > 0.40:
        recs.append("⚠️  Biaya pupuk > 40% total input. Pertimbangkan pupuk "
                    "organik atau program subsidi untuk efisiensi biaya.")
    if labor_ratio > 0.35:
        recs.append("⚠️  Biaya TK > 35% total input. Evaluasi mekanisasi "
                    "parsial (transplanter, combine harvester) untuk menekan biaya.")
    if land_area_m2 < 1500:
        recs.append("📌 Lahan sempit (<1.500 m²). Bergabung dengan kelompok tani "
                    "untuk pooling input dan negosiasi harga jual bersama.")
    if margin_pct < 25:
        recs.append("📌 Margin rendah. Tinjau harga jual vs HPP, eksplorasi "
                    "akses pasar langsung (bypass tengkulak).")
    if not recs:
        recs.append("✅ Profil produksi dalam kondisi baik. "
                    "Pertahankan pola manajemen saat ini.")

    return {
        "Wilayah":                  region,
        "Luas Lahan (m²)":          f"{land_area_m2:,.0f}",
        "Total Biaya Input (IDR)":  f"{total_input:,.0f}",
        "Prediksi Nilai Prod (IDR)":f"{pred_val:,.0f}",
        "Estimasi Profit (IDR)":    f"{profit:,.0f}",
        "Profit Margin (%)":        f"{margin_pct:.1f}%",
        "Pendapatan per m² (IDR)":  f"{rev_per_m2:,.0f}",
        "Kategori Efisiensi":       eff_cat,
        "Rekomendasi":              recs,
    }


# ── 8.2 Demo 3 Kasus ──────────────────────────────────────────────────────
kasus_list = [
    dict(
        land_area_m2=1000, land_lease_value=1750000, labor_cost=500000,
        seed_value=230000, fertilizer_value=1300000, pesticide_value=130000,
        equipment_rent=350000, region="Garut",
        _label="Petani Kecil — Garut (1.000 m²)",
    ),
    dict(
        land_area_m2=5000, land_lease_value=8750000, labor_cost=1500000,
        seed_value=1150000, fertilizer_value=6500000, pesticide_value=650000,
        equipment_rent=1200000, region="Karawang",
        _label="Petani Menengah — Karawang (5.000 m²)",
    ),
    dict(
        land_area_m2=10000, land_lease_value=17500000, labor_cost=4000000,
        seed_value=2300000, fertilizer_value=13000000, pesticide_value=1300000,
        equipment_rent=2190000, region="Indramayu",
        _label="Petani Besar — Indramayu (10.000 m²)",
    ),
]

print("=" * 68)
print("🚀  DEMO INFERENCE — 3 CONTOH KASUS NYATA")
print("=" * 68)

for kasus in kasus_list:
    label = kasus.pop("_label")
    result = predict_farmer_production(**kasus)
    print(f"\n  ── {label} {'─'*max(0, 50-len(label))}")
    for key, val in result.items():
        if key == "Rekomendasi":
            print(f"  {'Rekomendasi':<30}:")
            for r in val:
                print(f"    → {r}")
        else:
            print(f"  {key:<30}: {val}")


# ── 8.3 Batch Inference ───────────────────────────────────────────────────
def batch_predict(df_new: pd.DataFrame) -> pd.DataFrame:
    """
    Prediksi nilai produksi untuk banyak petani sekaligus.

    Parameters
    ----------
    df_new : DataFrame dengan kolom sesuai RF_FEATURE_COLS
             (tidak perlu sudah di-scale; fungsi ini menangani scaling)

    Returns
    -------
    DataFrame dengan kolom tambahan:
      predicted_production, estimated_profit, profit_margin_pct, efficiency_cat
    """
    df_new = df_new.copy()

    # Feature engineering jika belum ada
    if "total_input_cost" not in df_new.columns:
        farmer_inp_avail = [c for c in FARMER_INPUTS if c in df_new.columns]
        df_new["total_input_cost"] = df_new[farmer_inp_avail].sum(axis=1)
    if "cost_per_m2" not in df_new.columns:
        df_new["cost_per_m2"] = (df_new["total_input_cost"]
                                 / df_new["Land area (m2)"].replace(0, np.nan))
    if "fertilizer_ratio" not in df_new.columns:
        df_new["fertilizer_ratio"] = (df_new["Fertilizer purchase value (IDR)"]
                                      / df_new["total_input_cost"].replace(0, np.nan))
    if "labor_ratio" not in df_new.columns:
        df_new["labor_ratio"] = (df_new["Labor cost (IDR)"]
                                 / df_new["total_input_cost"].replace(0, np.nan))
    if "region_encoded" not in df_new.columns:
        df_new["region_encoded"] = df_new["region"].map(region_map).fillna(-1)

    X_new    = df_new[RF_FEATURE_COLS].fillna(0).values
    X_new_sc = _scaler_rf.transform(X_new)
    preds    = _rf_model.predict(X_new_sc)

    df_new["predicted_production"] = preds
    df_new["estimated_profit"]     = preds - df_new["total_input_cost"]
    df_new["profit_margin_pct"]    = (df_new["estimated_profit"]
                                      / df_new["predicted_production"].replace(0, np.nan) * 100)
    df_new["efficiency_cat"] = pd.cut(
        df_new["profit_margin_pct"],
        bins=[-np.inf, 25, 50, np.inf],
        labels=["Rendah", "Sedang", "Tinggi"]
    )
    return df_new


# Demo batch dengan 10 sampel acak dari test set
df_test_sample = df_rf.iloc[
    np.random.choice(len(df_rf), size=min(10, len(df_rf)), replace=False)
].copy()

df_batch_result = batch_predict(df_test_sample)
print("\n\n📋 DEMO BATCH INFERENCE — 10 Sampel Acak:")
show_batch = ["region", "Land area (m2)", "total_input_cost",
              "predicted_production", "profit_margin_pct", "efficiency_cat"]
show_batch = [c for c in show_batch if c in df_batch_result.columns]
print(df_batch_result[show_batch].round(1).to_string(index=False))

print("\n✅ [CELL 8] Inference & Implementasi selesai")

"""CONTOH PENGGUNAAN ? ( PROTOTYPE )"""

style  = {"description_width": "210px"}
layout = widgets.Layout(width="440px")

# ── Widget komponen ───────────────────────────────────────────────────────
w_region = widgets.Dropdown(
    options=REGIONS, value="Garut",
    description="Wilayah:", style=style, layout=layout)

w_area = widgets.FloatSlider(
    value=2000, min=100, max=30000, step=100,
    description="Luas Lahan (m²):",
    style=style, layout=layout, readout_format=",d")

w_lease = widgets.FloatSlider(
    value=3500000, min=100000, max=60000000, step=100000,
    description="Sewa Lahan (IDR):",
    style=style, layout=layout, readout_format=",d")

w_labor = widgets.FloatSlider(
    value=1000000, min=50000, max=30000000, step=50000,
    description="Biaya TK (IDR):",
    style=style, layout=layout, readout_format=",d")

w_seed = widgets.FloatSlider(
    value=460000, min=10000, max=8000000, step=10000,
    description="Biaya Benih (IDR):",
    style=style, layout=layout, readout_format=",d")

w_fert = widgets.FloatSlider(
    value=2600000, min=100000, max=50000000, step=100000,
    description="Biaya Pupuk (IDR):",
    style=style, layout=layout, readout_format=",d")

w_pest = widgets.FloatSlider(
    value=260000, min=10000, max=6000000, step=10000,
    description="Biaya Pestisida (IDR):",
    style=style, layout=layout, readout_format=",d")

w_equip = widgets.FloatSlider(
    value=690000, min=10000, max=8000000, step=10000,
    description="Sewa Alat (IDR):",
    style=style, layout=layout, readout_format=",d")

btn    = widgets.Button(
    description="🔍  Prediksi Sekarang",
    button_style="success",
    layout=widgets.Layout(width="220px", height="40px"))

output_box = widgets.Output()


def render_gauge(margin_pct: float) -> str:
    """Render SVG gauge mini untuk efisiensi."""
    pct   = max(0, min(100, margin_pct))
    color = "#27AE60" if pct >= 50 else ("#F39C12" if pct >= 25 else "#C73E1D")
    width = int(pct * 2.5)   # max bar width = 250px
    return f"""
    <div style='margin-top:10px;font-family:monospace;'>
      <b>Profit Margin Gauge</b><br>
      <div style='background:#eee;width:250px;height:22px;border-radius:4px;overflow:hidden;'>
        <div style='background:{color};width:{width}px;height:22px;
                    border-radius:4px;transition:width 0.4s;'></div>
      </div>
      <span style='color:{color};font-weight:bold;'>{pct:.1f}%</span>
    </div>"""


def on_predict(_):
    with output_box:
        clear_output(wait=True)
        try:
            res = predict_farmer_production(
                land_area_m2     = w_area.value,
                land_lease_value = w_lease.value,
                labor_cost       = w_labor.value,
                seed_value       = w_seed.value,
                fertilizer_value = w_fert.value,
                pesticide_value  = w_pest.value,
                equipment_rent   = w_equip.value,
                region           = w_region.value,
            )
            # Tabel HTML hasil
            rows_html = ""
            recs_html = ""
            for k, v in res.items():
                if k == "Rekomendasi":
                    recs_html = "".join(f"<li>{r}</li>" for r in v)
                else:
                    rows_html += (
                        f"<tr>"
                        f"<td style='padding:5px 14px;font-weight:600;"
                        f"border-bottom:1px solid #ddd;'>{k}</td>"
                        f"<td style='padding:5px 14px;"
                        f"border-bottom:1px solid #ddd;'>{v}</td>"
                        f"</tr>"
                    )
            # Ambil nilai margin untuk gauge
            margin_val = float(
                res["Profit Margin (%)"].replace("%", "").strip()
            )
            gauge_html = render_gauge(margin_val)
            html_out = f"""
            <div style='font-family:sans-serif;font-size:13px;'>
              <h3 style='color:#2E86AB;margin-bottom:6px;'>
                Hasil Prediksi — {res['Wilayah']}
              </h3>
              <table border='0' cellspacing='0' style='border-collapse:collapse;
                     background:#fafafa;border:1px solid #ddd;border-radius:6px;
                     overflow:hidden;'>
                {rows_html}
              </table>
              {gauge_html}
              <h4 style='margin-top:14px;color:#555;'>Rekomendasi:</h4>
              <ul style='line-height:1.8;'>{recs_html}</ul>
            </div>"""
            display(HTML(html_out))
        except Exception as err:
            display(HTML(f"<p style='color:red;'><b>❌ Error:</b> {err}</p>"))


btn.on_click(on_predict)

# ── Susun layout form ────────────────────────────────────────────────────
header_html = widgets.HTML(
    "<h3 style='color:#2E86AB;font-family:sans-serif;'>"
    "🌾 Prediksi Nilai Produksi Petani Jawa Barat</h3>"
    "<p style='color:#666;font-size:12px;font-family:sans-serif;'>"
    "Atur parameter di bawah lalu klik tombol Prediksi.</p>"
)

form = widgets.VBox([
    header_html,
    w_region, w_area, w_lease, w_labor,
    w_seed,   w_fert,  w_pest,  w_equip,
    btn, output_box
], layout=widgets.Layout(padding="16px", max_width="500px"))

display(form)
print("✅ [CELL 9] Widget interaktif ditampilkan")

"""
STREAMLIST"""

#pip install streamlit

"""KESIMPULAN"""

r2_test   = r2_score(y_test, y_pred_test)
rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
mape_test = mape_score(y_test, y_pred_test)
mean_dea  = df_dea_all["dea_score"].mean()
anom_pct_total = (df_iso["anomaly"] == -1).mean() * 100
best_region_dea = dea_stats["Mean"].idxmax()
worst_region_dea= dea_stats["Mean"].idxmin()
top_feature     = pd.Series(rf_model.feature_importances_,
                             index=RF_FEATURE_COLS).idxmax()

print(f"""
╔══════════════════════════════════════════════════════════════════════╗
║              📝  BAB 3 — KESIMPULAN                                  ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║  1. EFISIENSI RANTAI PASOK (Model A — DEA)                           ║
║     • Rata-rata skor DEA keseluruhan petani : {mean_dea:.3f}         ║
║     • Wilayah efisiensi TERTINGGI : {best_region_dea:<25}            ║
║     • Wilayah efisiensi TERENDAH  : {worst_region_dea:<25}           ║
║     → Karawang & Indramayu unggul berkat skala lahan lebih besar     ║
║       dan biaya input yang lebih terkelola dibanding Garut/Subang.   ║
║                                                                      ║
║  2. FAKTOR PENENTU PRODUKSI (Model B — Random Forest)                ║
║     • R² Test    : {r2_test:.4f}                                     ║
║     • RMSE Test  : {rmse_test/1e6:.2f} Juta IDR                      ║
║     • MAPE Test  : {mape_test:.2f}%                                  ║
║     • Fitur paling penting : {top_feature:<30}                       ║
║     → SHAP mengkonfirmasi luas lahan dan total biaya input           ║
║       sebagai driver utama nilai produksi.                           ║
║                                                                      ║
║  3. DETEKSI ANOMALI (Model C — Isolation Forest)                     ║
║     • {anom_pct_total:.1f}% DMU di seluruh rantai pasok terdeteksi anomali.       ║
║     • Middlemen (Tengkulak) memiliki proporsi anomali tertinggi.     ║
║     → Pola margin tengkulak yang tidak konsisten perlu transparansi  ║
║       harga dan pengawasan lebih ketat dari pemangku kebijakan.      ║
║                                                                      ║
║  4. REKOMENDASI KEBIJAKAN                                            ║
║     ✦ Subsidi pupuk berbasis kebutuhan aktual per wilayah            ║
║     ✦ Dorong mekanisasi di wilayah dengan biaya TK tinggi            ║
║     ✦ Program konsolidasi lahan untuk petani kecil (<1.500 m²)       ║
║     ✦ Transparansi harga antar aktor untuk kurangi anomali           ║
║     ✦ Platform digital rantai pasok: petani → penggilingan langsung  ║
║                                                                      ║
║  5. KETERBATASAN & PENGEMBANGAN LANJUTAN                             ║
║     • Dataset statis; integrasikan data musim/curah hujan (dinamis)  ║
║     • Gunakan BCC-DEA untuk model skala variabel (VRS)               ║
║     • Forecasting harga beras menggunakan LSTM / Prophet             ║
║     • Deployment pipeline inferensi ke REST API (FastAPI/Flask)      ║
╚══════════════════════════════════════════════════════════════════════╝
""")

joblib.dump(rf_model, "models/rf_farmer_model.pkl")